export const DOMAIN_POLLING_MS = 10_000;

export const CURRENT_TIME_REFRESH_MS = 60_000;

export const STORAGE_SETTLE_DELAY_MS = 100;

export const STORAGE_LOADED_TIMEOUT_MS = 100;

export const STALE_ENTRY_TIMEOUT_MS = 60 * 1_000;

export const ALARM_DAILY_CLEANUP_MINUTES = 60;

export const ALARM_CHECK_SCHEDULE_MINUTES = 1;

export const MAX_HISTORY_DAYS_FALLBACK = 365;

export const MS_PER_DAY = 1_000 * 60 * 60 * 24;

export const STATUS_RESET_DELAY_MS = 2_000;

export const REFRESH_SPINNER_DELAY_MS = 500;

export const EXPORT_STATUS_DELAY_MS = 3_000;

export const SHARE_MESSAGE_DELAY_MS = 5_000;
