/**
 * Plasmo messaging type augmentation.
 *
 * In local development, `.plasmo/messaging.d.ts` is auto-generated by
 * `plasmo dev` / `plasmo build` and provides these types. However, CI
 * runs `tsc --noEmit` before the build step, so the generated file is
 * not available. This file provides the same module augmentation so
 * type-checking passes in both environments.
 *
 * Keep this in sync with `src/background/messages/` handlers.
 */
import '@plasmohq/messaging';

declare module '@plasmohq/messaging' {
  interface MessagesMetadata {
    'add-block': object;
    'get-remaining-time': object;
    'get-stats': object;
    'remove-block': object;
    'toggle-block': object;
    'toggle-pause': object;
    'tracker-heartbeat': object;
    'update-time-limit': object;
  }
}
