import { onMessage } from '~/lib/messaging';
import { addAllowedSiteHandler } from './add-allowed-site';
import { addBlockHandler } from './add-block';
import { addScheduleHandler } from './add-schedule';
import { addTrackedSiteHandler } from './add-tracked-site';
import { applyPresetHandler } from './apply-preset';
import { createPresetHandler } from './create-preset';
import { deletePresetHandler } from './delete-preset';
import { getRemainingTimeHandler } from './get-remaining-time';
import { importSettingsHandler } from './import-settings';
import { removeBlockHandler } from './remove-block';
import { removeScheduleHandler } from './remove-schedule';
import { resetActivityHandler } from './reset-activity';
import { setAllowedSiteRecordingHandler } from './set-allowed-site-recording';
import { stopTrackingHandler } from './stop-tracking';
import { toggleBlockHandler } from './toggle-block';
import { toggleScheduleHandler } from './toggle-schedule';
import { trackerHeartbeatHandler } from './tracker-heartbeat';
import { updateAnalyticsOptInHandler } from './update-analytics-opt-in';
import { updateGoalTextHandler } from './update-goal-text';
import { updateNotificationsHandler } from './update-notifications';
import { updatePresetHandler } from './update-preset';
import { updateScheduleHandler } from './update-schedule';
import { updateTimeLimitHandler } from './update-time-limit';
import { updateUnblockConfirmHandler } from './update-unblock-confirm';
import { updateYouTubeSettingsHandler } from './update-youtube-settings';
import { setPasswordHandler } from './set-password';
import { changePasswordHandler } from './change-password';
import { removePasswordHandler } from './remove-password';

/** background が受けるメッセージごとにハンドラを登録する */
export function registerMessageHandlers(): void {
  onMessage('add-allowed-site', addAllowedSiteHandler);
  onMessage('add-block', addBlockHandler);
  onMessage('add-schedule', addScheduleHandler);
  onMessage('add-tracked-site', addTrackedSiteHandler);
  onMessage('apply-preset', applyPresetHandler);
  onMessage('create-preset', createPresetHandler);
  onMessage('delete-preset', deletePresetHandler);
  onMessage('get-remaining-time', getRemainingTimeHandler);
  onMessage('import-settings', importSettingsHandler);
  onMessage('remove-block', removeBlockHandler);
  onMessage('remove-schedule', removeScheduleHandler);
  onMessage('reset-activity', resetActivityHandler);
  onMessage('set-allowed-site-recording', setAllowedSiteRecordingHandler);
  onMessage('stop-tracking', stopTrackingHandler);
  onMessage('toggle-block', toggleBlockHandler);
  onMessage('toggle-schedule', toggleScheduleHandler);
  onMessage('tracker-heartbeat', trackerHeartbeatHandler);
  onMessage('update-analytics-opt-in', updateAnalyticsOptInHandler);
  onMessage('update-goal-text', updateGoalTextHandler);
  onMessage('update-notifications', updateNotificationsHandler);
  onMessage('update-preset', updatePresetHandler);
  onMessage('update-schedule', updateScheduleHandler);
  onMessage('update-time-limit', updateTimeLimitHandler);
  onMessage('update-unblock-confirm', updateUnblockConfirmHandler);
  onMessage('update-youtube-settings', updateYouTubeSettingsHandler);
  onMessage('set-password', setPasswordHandler);
  onMessage('change-password', changePasswordHandler);
  onMessage('remove-password', removePasswordHandler);
}
